### ISSUE TITLE
config.txt missing

### ISSUE THREAD

**Issue by MKliesch** [hlefebvr/tx-gtfs#2]
Hi there,

I was trying to get your script to run and ended up with the error "FileNotFoundError:... main\\model/config.txt", and I noticed that your .gitignore includes .txt. Could you upload the respective file?

**Comment by hlefebvr** [comment]
Hi there,

I edited the code. Now there is no need for an initial config.txt file and it will be created automatically. 

Note that I also moved from PyQt4 to PyQt5 because PyQt4 is no longer supported by pip3.

I tested on the instance from: https://navitia.opendatasoft.com/explore/dataset/fr-idf/table/?sort=type_file, and everything seems to be working. 

Thanks!
